FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake libpng-dev libjpeg-dev libtiff-dev libavcodec-dev libavformat-dev libsamplerate0-dev libswscale-dev libsndfile-dev

COPY . /repo
WORKDIR /repo/build
RUN cmake .. -DPHASH_EXAMPLES=1 -DWITH_AUDIO_HASH=1 -DWITH_VIDEO_HASH=1
RUN make -j8
